VetWebApp/Controllers/AboutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace VetWebApp.Controllers
{
	public class AboutController : Controller
	{
		// GET: /About/
		public IActionResult About()
		{
			return View();
		}
	}
}

VetWebApp/Controllers/LocateController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace VetWebApp.Controllers
{
    public class LocateController : Controller
    {
        // GET: /Locate/
        public IActionResult Locate()
        {
            return View();
        }
    }
}

VetWebApp/Controllers/ServicesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace VetWebApp.Controllers
{
    public class ServicesController : Controller
    {
        // GET: /Services/
        public IActionResult Services()
        {
            return View();
        }
    }
}

VetWebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Vet App</title>
    <link rel="stylesheet" href="~/Content/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/Content/css/styles.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-light border-bottom box-shadow mb-3">
            <div class="container-fluid font-access">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Home">Vet App</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="About" asp-action="About">About</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Services" asp-action="Services">Services</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Locate" asp-action="Locate">Locate</a>
                        </li>
                    </ul>
                    <div class="navbar-nav my-2 my-lg-0">
                        <div class="dropdown">
                            <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Change Background
                            </button>
                            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                <a class="dropdown-item" href="#" onclick="resetImage()">None</a>
                                <a class="dropdown-item" href="#" onclick="setImage('dog')">Dog</a>
                                <a class="dropdown-item" href="#" onclick="setImage('cat')">Cat</a>
                                <a class="dropdown-item" href="#" onclick="setImage('both')">Both</a>
                            </div>
                        </div>
                    </div>
                    <partial name="_LoginPartial"></partial>
                </div>
            </div>
        </nav>
    </header>
    <div class="container bg-white rounded p-3 bg-img">
        <main role="main">
            @RenderBody()
        </main>
    </div>
    <footer class="border-top footer text-muted bg-light">
        <div class="container">
            &copy; 2023 - Vet App
        </div>
    </footer>
    <script src="~/Content/lib/jquery/dist/jquery.js"></script>
    <script src="~/Content/lib/bootstrap/dist/js/bootstrap.js"></script>
    <script src="~/Content/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>